config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users
  resources :posts, only: [:new, :create, :index, :show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Welcome to Members Only!</h1>
<h2>Posts</h2>

<% @posts.each do |post| %>
  <ul>
    <li><%= link_to post.title, post_path(post) %></li>
    <% if user_signed_in? %>
      <li>by: <%= post.user.email %></li>
    <% end %>
  </ul>
<% end %>

<br><br>

<% if user_signed_in?  %>
  <%= link_to "New Post", new_post_path %><br>
  <%= link_to "Sign Out", destroy_user_session_path, 'data-turbo-method': :delete %>
<% else %>
  <%= link_to "Sign in", new_user_session_path %>
<% end %>

app/views/posts/new.html.erb
<%= form_with model: @post do |form| %>
  <%= form.label :title, "Title" %><br>
  <%= form.text_field :title %><br><br>
  <%= form.label :content, "Body" %> <br>
  <%= form.text_area :content, size: "50x5" %><br><br>
  <%= form.submit "Submit" %>
<% end %>

<br>
<%= link_to "Home", root_path %>

app/views/posts/show.html.erb
<%= @post.title %><br><br>
<%= @post.content%>

<br><br>
<%= link_to "Home", root_path %>